{"name": "test_another_failed_t", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@pytest.mark.staging\n    @pytest.mark.production\n    def test_another_failed_t():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests\\users\\test_users.py:33: AssertionError"}, "start": 1709819119164, "stop": 1709819119164, "uuid": "fcd94479-334c-4d2a-9995-9d070ae7f6dd", "historyId": "f17f41a874c494b7a469426f7ad80adf", "testCaseId": "f17f41a874c494b7a469426f7ad80adf", "fullName": "tests.users.test_users#test_another_failed_t", "labels": [{"name": "tag", "value": "production"}, {"name": "tag", "value": "staging"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-8NHQB09"}, {"name": "thread", "value": "2872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}